spring.application.name=destinos-api

# Configurações do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/destinos_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate vai ser utilizado para criar as tabelas no banco de dados, caso elas não existam. O valor "update" indica que o Hibernate deve atualizar o esquema do banco de dados automaticamente com base nas entidades mapeadas.
spring.jpa.hibernate.ddl-auto=update

# O Hibernate Dialect é uma configuração que informa ao Hibernate como gerar o SQL específico para o banco de dados que está sendo utilizado. 
#No caso, estamos utilizando o PostgreSQL, então configuramos o dialect para org.hibernate.dialect.PostgreSQLDialect.
spring.jpa,properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

